export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";

export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH_SINGLE_MOVIE_SUCCESS";
export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH_SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_FAIL = "FETCH_SINGLE_MOVIE_FAIL";
